import os
import gc
import abc

import cadquery as cq
import numpy as np
import scipy

# Use geomdl for B-spline basis helpers.
from geomdl import knotvector as geomdl_kv
from geomdl import helpers    as geomdl_helpers
from geomdl import BSpline    as geomdl_BSpline

from OCP.Geom           import Geom_BSplineSurface
from OCP.BRepMesh       import BRepMesh_IncrementalMesh
from OCP.IGESControl    import IGESControl_Writer
from OCP.STEPControl    import STEPControl_Writer, STEPControl_AsIs
from OCP.gp             import gp_Pnt, gp_Trsf
from OCP.TColgp         import TColgp_Array2OfPnt
from OCP.TColStd        import TColStd_Array1OfReal, TColStd_Array1OfInteger
from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace
from OCP.BRepOffsetAPI  import BRepOffsetAPI_ThruSections

_HERE = os.path.dirname(os.path.abspath(__file__))


# =========================================================
# B-spline helpers backed by geomdl
# =========================================================

def make_uniform_knots(n_ctrl: int, degree: int) -> list:
    """
    Generate a clamped uniform knot vector.
    """
    return geomdl_kv.generate(degree, n_ctrl)


def find_span(n: int, p: int, u: float, U) -> int:
    return geomdl_helpers.find_span_linear(n, p, u, list(U))


def basis_funs(span: int, u: float, p: int, U) -> np.ndarray:
    return np.array(
        geomdl_helpers.basis_function(p, list(U), span, u)
    )

def trivariate_evaluate(ctrl_pts: np.ndarray,
                        knots_u, knots_v, knots_w,
                        degree: int,
                        u: float, v: float, w: float) -> np.ndarray:
    """
    ctrl_pts: shape (nu+1, nv+1, nw+1, 3), axis order (u, v, w)
    """
    nu1, nv1, nw1, _ = ctrl_pts.shape

    vol = geomdl_BSpline.Volume()

    # Step 1: set the degree first.
    vol.degree_u = degree
    vol.degree_v = degree
    vol.degree_w = degree

    # Step 2: set all control point counts through cpsize.
    # geomdl expects cpsize here, not ctrlpts_size_u/v/w.
    vol.cpsize = [nu1, nv1, nw1]

    # Step 3: flatten control points in geomdl u-v-w order.
    # Shape is (nu1 * nv1 * nw1, 3).
    flat_ctrlpts = ctrl_pts.reshape(-1, 3).tolist()
    vol.ctrlpts = flat_ctrlpts

    # Step 4: assign knot vectors after control points.
    vol.knotvector_u = list(knots_u)
    vol.knotvector_v = list(knots_v)
    vol.knotvector_w = list(knots_w)

    # Evaluate the clipped parameter point.
    u_c = float(np.clip(u, 0.0, 1.0))
    v_c = float(np.clip(v, 0.0, 1.0))
    w_c = float(np.clip(w, 0.0, 1.0))

    result = vol.evaluate_single((u_c, v_c, w_c))
    return np.array(result)

# =========================================================
# Iso-surface extraction
# =========================================================

def extract_iso_surface(coefs_list, w_knots, degree_w, w):
    coefs = np.stack(coefs_list, axis=3)
    _, nu, nv, num = coefs.shape
    n_w  = num - 1
    span = find_span(n_w, degree_w, w, w_knots)
    N    = basis_funs(span, w, degree_w, w_knots)
    idx_start = span - degree_w
    relevant  = coefs[:, :, :, idx_start : idx_start + degree_w + 1]
    return np.tensordot(relevant, N, axes=([3], [0]))

# =========================================================
# Convert to OCC format.
# =========================================================

def convert_knots(knots_flat, degree):
    """Flatten a knot vector into unique values and multiplicities."""
    knots = np.asarray(knots_flat, dtype=float)
    uniq, mult = [], []
    prev, count = knots[0], 1
    for k in knots[1:]:
        if np.isclose(k, prev, atol=1e-12):
            count += 1
        else:
            uniq.append(prev); mult.append(count)
            prev, count = k, 1
    uniq.append(prev); mult.append(count)
    return np.array(uniq), np.array(mult)


def to_occ_real_array(arr):
    oc = TColStd_Array1OfReal(1, len(arr))
    for i, v in enumerate(arr):
        oc.SetValue(i + 1, float(v))
    return oc


def to_occ_int_array(arr):
    oc = TColStd_Array1OfInteger(1, len(arr))
    for i, v in enumerate(arr):
        oc.SetValue(i + 1, int(v))
    return oc


def build_occ_bspline_face(pts_grid: np.ndarray,
                            degree: int = 3):
    """
    Convert an (n, n, 3) point grid into an OCC B-spline face.
    Knot vectors are generated by geomdl and converted to OCC arrays here.
    """
    n     = pts_grid.shape[0]
    knots = make_uniform_knots(n, degree)          # Generated by geomdl.
    u_uniq, u_mult = convert_knots(knots, degree)  # Convert to OCC format.

    poles = TColgp_Array2OfPnt(1, n, 1, n)
    for i in range(n):
        for j in range(n):
            x, y, z = pts_grid[i, j]
            poles.SetValue(i + 1, j + 1, gp_Pnt(float(x), float(y), float(z)))

    surf = Geom_BSplineSurface(
        poles,
        to_occ_real_array(u_uniq), to_occ_real_array(u_uniq),
        to_occ_int_array(u_mult),  to_occ_int_array(u_mult),
        degree, degree, False, False
    )
    return BRepBuilderAPI_MakeFace(surf, 1e-6).Shape()

# =========================================================
# Geometry helper
# =========================================================
def make_location_from_matrix(T: np.ndarray, scale: float = 1.0) -> cq.Location:
    """
    Convert a 4x4 homogeneous transform matrix to a CadQuery location.
    The translation column is scaled by the unit-cell size in millimeters.
    """
    R = T[:3, :3]
    t = T[:3,  3] * scale
    trsf = gp_Trsf()
    trsf.SetValues(
        R[0,0], R[0,1], R[0,2], t[0],
        R[1,0], R[1,1], R[1,2], t[1],
        R[2,0], R[2,1], R[2,2], t[2],
    )
    return cq.Location(trsf)


def apply_T(shape: cq.Shape,
            T: np.ndarray, scale: float = 1.0) -> cq.Shape:
    return shape.located(make_location_from_matrix(T, scale))

# =========================================================
# Export helper
# =========================================================

def export_shape(wp_shape, export_dir, stem, export_type):
    os.makedirs(export_dir, exist_ok=True)
    ext = export_type.upper()

    if ext == "STEP":
        filename = os.path.join(export_dir, f"{stem}.step")
        writer = STEPControl_Writer()
        writer.Transfer(wp_shape, STEPControl_AsIs)
        writer.Write(filename)

    elif ext == "IGES":
        filename = os.path.join(export_dir, f"{stem}.igs")
        writer = IGESControl_Writer()
        writer.AddShape(wp_shape)
        writer.Write(filename)

    elif ext == "STL":
        filename = os.path.join(export_dir, f"{stem}.stl")
        mesh = BRepMesh_IncrementalMesh(
            wp_shape,
            0.01,  # Linear deflection.
            False,  # Use absolute, not relative, deflection.
            0.1,  # Angular deflection.
            True  # Enable parallel meshing.
        )
        mesh.Perform()
        cq.Shape(wp_shape).exportStl(filename)

    else:
        raise ValueError(
            f"Unsupported export format: '{export_type}'. Use STEP, IGES, or STL."
        )

    print(f"Exported: {os.path.abspath(filename)}")
